app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from app.company_admin import company_admin_site

# Garante que apenas superusuários possam acessar a rota /admin/
admin.site.has_permission = lambda r: r.user.is_superuser


urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', company_admin_site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.home, name='home'),

    path('', include('brands.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
    path('', include('predictions.urls')),
]

outflows/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('outflows/list/', views.OutflowListView.as_view(), name='outflow_list'),
    path('outflows/create/', views.OutflowCreateView.as_view(), name='outflow_create'),
    path('outflows/<int:pk>/detail/', views.OutflowDetailView.as_view(), name='outflow_detail'),
]

outflows/models.py
from django.db import models
from companyusers.models import CompanyUser
from products.models import Product


class Outflow(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='outflows')
    companyuser = models.ForeignKey(CompanyUser, on_delete=models.CASCADE, related_name='outflows')
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

outflows/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models
from products.models import Product


class OutflowForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # Pega o usuário que foi passado pela view
        user = kwargs.pop('user', None)
        super(OutflowForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['product'].queryset = Product.objects.filter(companyuser=user.companyusers)

    class Meta:
        model = models.Outflow
        fields = ['product', 'quantity', 'description']
        widgets = {
            'product': forms.Select(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
        labels = {
            'product': 'Produto',
            'quantity': 'Quantidade',
            'description': 'Descrição'
        }

    def clean(self):
        cleaned_data = super().clean()
        quantity = cleaned_data.get('quantity')
        product = cleaned_data.get('product')

        if quantity and product:
            if quantity > product.quantity:
                raise ValidationError(
                    f'A quantidade disponível em estoque para o produto {product.title} é de {product.quantity} unidades'
                )
        return cleaned_data

outflows/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models, forms
from app import metrics


class OutflowListView(LoginRequiredMixin, ListView):
    model = models.Outflow
    template_name = 'outflow_list.html'
    context_object_name = 'outflows'
    paginate_by = 4

    def get_queryset(self):
        # Pega a empresa do usuário logado
        company = self.request.user.companyusers.company
        # Filtra as saídas para mostrar apenas as da empresa do usuário logado
        queryset = models.Outflow.objects.filter(companyuser__company=company)

        product = self.request.GET.get('product')

        if product:
            queryset = queryset.filter(product__title__icontains=product)
        return queryset

    def get_context_data(self, **kwargs):
        company = self.request.user.companyusers.company
        context = super().get_context_data(**kwargs)
        context['sales_metrics'] = metrics.get_sales_metrics(company)
        context['company'] = company
        return context


class OutflowCreateView(LoginRequiredMixin, CreateView):
    model = models.Outflow
    template_name = 'outflow_create.html'
    form_class = forms.OutflowForm
    success_url = reverse_lazy('outflow_list')

    def form_valid(self, form):
        form.instance.companyuser = self.request.user.companyusers
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(OutflowCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class OutflowDetailView(LoginRequiredMixin, DetailView):
    model = models.Outflow
    template_name = 'outflow_detail.html'

outflows/templates/outflow_create.html
{% extends 'exemplo.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="h-4">Cadastrar Saída</h3>
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-custom">Criar Saída</button>
            </form>
            <a href="{% url 'outflow_list' %}" class="btn bg-danger-subtle mt-3 text-danger-emphasis">Voltar para a Lista de Saídas</a>
        </div>
    </div>
    
</div>

{% endblock %}

outflows/templates/outflow_detail.html
{% extends 'exemplo.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="h-4">Detalhes da Saída</h3>
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{object.product}}</h3>  
            <p class="card-text">Data da Saída: <strong>{{object.created_at}}</strong></p>
            <p class="card-text">Quantidade: <strong>{{object.quantity}}</strong></p>
            <p class="card-text">{{object.description}}</p>
        </div>
    </div>
    <a href="{% url 'outflow_list' %}" class="btn bg-danger-subtle mt-3 text-danger-emphasis">Voltar para a Lista de Saídas</a>
</div>

{% endblock %}

outflows/templates/outflow_list.html
{% extends 'exemplo.html' %}

{% block title %}
    Gestão de Estoque - Saídas
{% endblock %}

{% block content %}
    <div class="container-fluid my-2 text-custom">
        <h2 class="h2">{{ company }}</h2>
    </div>
    {% if perms.outflows.view_outflow %}
        {% include 'components/_sales_metrics.html' %}
    {% endif %}
    <div class="row d-md-flex justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6 mx-auto my-4">
            <div class="">
                <form action="{% url 'outflow_list' %}" method="get" class="input-group shadow-sm">
                    <div class="input-group">
                        <input type="text" name="product" placeholder="Produto" class="form-control" value="{{ request.GET.product }}">
                        <button type="submit" class="btn bg-success-subtle">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Button -->
        <div class="col-12 col-md-8 col-lg-6 mx-auto my-4">
            <a href="{% url 'outflow_create' %}" class="btn btn-custom w-100">
                <i class="bi bi-plus-circle"></i> Nova Saída
            </a>
        </div>
    </div>
        

    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th>ID</th>
                                    <th>PRODUTO</th>
                                    <th class="d-none d-lg-table-cell">DATA DA SAÍDA</th>
                                    <th class="d-none d-lg-table-cell">QUANTIDADE</th>
                                    <th class="text-center" colspan="3">AÇÕES</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for outflow in outflows %}
                                <tr>
                                    <td>{{outflow.id}}</td>
                                    <td>{{outflow.product}}</td>
                                    <td class="d-none d-lg-table-cell">{{outflow.created_at}}</td>
                                    <td class="d-none d-lg-table-cell">{{outflow.quantity}}</td>
                                    <td class="text-center">
                                        <div class="btn-group" role="group">
                                            <a href="{% url 'outflow_detail' outflow.id %}" class="btn btn-info btn-sm mx-1">
                                                <i class="bi bi-eye"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% include 'components/_pagination.html' %}
{% endblock %}