app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from app.company_admin import company_admin_site

# Garante que apenas superusuários possam acessar a rota /admin/
admin.site.has_permission = lambda r: r.user.is_superuser


urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', company_admin_site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.home, name='home'),

    path('', include('brands.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
    path('', include('predictions.urls')),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('products/list/', views.ProductListView.as_view(), name='product_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/detail/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
]

inflows/models.py
from django.db import models
from companyusers.models import CompanyUser
from products.models import Product


class Inflow(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='inflows')
    companyuser = models.ForeignKey(CompanyUser, on_delete=models.CASCADE, related_name='inflows')
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

products/models.py
from django.db import models
from companyusers.models import CompanyUser
from brands.models import Brand


class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    companyuser = models.ForeignKey(CompanyUser, on_delete=models.CASCADE, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products')
    cost_price = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from . import models
from brands.models import Brand


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # Pega o usuário que foi passado pela view
        user = kwargs.pop('user', None)
        super(ProductForm, self).__init__(*args, **kwargs)

        # Filtra o queryset do campo 'brand'
        if user:
            self.fields['brand'].queryset = Brand.objects.filter(companyuser=user.companyusers)

    class Meta:
        model = models.Product
        fields = ['title', 'brand', 'description', 'cost_price', 'selling_price']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'brand': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'cost_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'selling_price': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Título',
            'brand': 'Marca',
            'description': 'Descrição',
            'cost_price': 'Preço de Custo',
            'selling_price': 'Preço de Venda',
        }

products/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models, forms
from brands.models import Brand
from app import metrics


class ProductListView(LoginRequiredMixin, ListView):
    model = models.Product
    template_name = 'product_list.html'
    context_object_name = 'products'
    paginate_by = 4

    def get_queryset(self):
        # Pega a emprea do usuário logado
        company = self.request.user.companyusers.company
        # Filtra os produtos para mostrar apenas os da empresa do usuário logado
        queryset = models.Product.objects.filter(companyuser__company=company)

        title = self.request.GET.get('title')
        brand = self.request.GET.get('brand')

        if title:
            queryset = queryset.filter(title__icontains=title)

        if brand:
            queryset = queryset.filter(brand__id=brand)

        return queryset

    def get_context_data(self, **kwargs):
        company = self.request.user.companyusers.company
        context = super().get_context_data(**kwargs)
        context['product_metrics'] = metrics.get_product_metrics(company)
        context['brands'] = Brand.objects.all()
        context['company'] = company
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = models.Product
    template_name = 'product_create.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')

    def form_valid(self, form):
        form.instance.companyuser = self.request.user.companyusers
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ProductCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = models.Product
    template_name = 'product_detail.html'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Product
    template_name = 'product_update.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')

    def get_form_kwargs(self):
        kwargs = super(ProductUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('product_list')

products/templates/product_create.html
{% extends 'exemplo.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="h-4">Cadastrar Produto</h3>
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-custom">Salvar Produto</button>
            </form>
            <a href="{% url 'product_list' %}" class="btn bg-danger-subtle mt-3 text-danger-emphasis">Voltar para a Lista de Produtos</a>
        </div>
    </div>    
</div>

{% endblock %}

products/templates/product_delete.html
{% extends 'exemplo.html' %}

{% block content %}
    <div class="container">
        <h3 class="h-4">Deletar Produto</h3>
        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja deletar o produto <strong>{{object.title}}</strong>?</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">DELETAR</button>
                </form>
            </div>
        </div>
        <a href="{% url 'product_list' %}" class="btn bg-info-subtle text-info-emphasis mt-3">Voltar para a Lista de Produtos</a>
    </div>
{% endblock %}

products/templates/product_detail.html
{% extends 'exemplo.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="h-4">Detalhes do Produto</h3>
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{object.title}}</h3>  
            <p class="card-text">Marca: {{object.brand}}</p>
            <p class="card-text">Preço de Custo: {{object.cost_price}}</p>
            <p class="card-text">Preço de Venda: {{object.selling_price}}</p>
            <p class="card-text">Quantidade em Estoque: {{object.quantity}}</p>
            <p class="card-text">{{object.description}}</p>
        </div>
    </div>
    <a href="{% url 'product_list' %}" class="btn bg-danger-subtle mt-3 text-danger-emphasis">Voltar para a Lista de Produtos</a>
</div>

{% endblock %}

products/templates/product_list.html
{% extends 'exemplo.html' %}

{% block title %}
    Gestão de Estoque - Produtos
{% endblock %}

{% block content %}
    <div class="container-fluid my-2 text-custom">
        <h2 class="h2">{{ company }}</h2>
    </div>
    {% if perms.products.view_product and perms.inflows.view_inflow %}
        {% include 'components/_products_metrics.html' %}
    {% endif %}
    <div class="row d-md-flex justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6 mx-auto my-4">
            <div class="">
                <form action="{% url 'product_list' %}" method="get" class="input-group shadow-sm">
                    <div class="input-group">
                        <input type="text" name="title" placeholder="Título" class="form-control" value="{{ request.GET.title }}">
                        <button type="submit" class="btn bg-success-subtle">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Button -->
        <div class="col-12 col-md-8 col-lg-6 mx-auto my-4">
            <a href="{% url 'product_create' %}" class="btn btn-custom w-100">
                <i class="bi bi-plus-circle"></i> Novo Produto
            </a>
        </div>
    </div>
        
    <div class="row mb-3">
        <div class="col-md-6">
            <form action="{% url 'product_list' %}" method="get">
                <div class="input-group">
                    <select name="brand" class="form-select">
                        <option value="" {% if not request.GET.brand %} selected {% endif %}>Todas as Marcas</option>
                        {% for brand in brands %}
                            <option value="{{brand.id}}" {% if reques.GET.brand == brand.id|stringformat:"s" %} selected {% endif %}>{{brand.name}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn bg-success-subtle">
                        <i class="bi bi-filter">Filtrar</i>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th>ID</th>
                                    <th>TÍTULO</th>
                                    <th>MARCA</th>
                                    <th>QUANTIDADE</th>
                                    <th class="d-none d-lg-table-cell">PREÇO DE CUSTO</th>
                                    <th class="d-none d-lg-table-cell">PREÇO DE VENDA</th>
                                    <th class="d-none d-lg-table-cell">DESCRIÇÃO</th>
                                    <th class="text-center" colspan="3">AÇÕES</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                <tr>
                                    <td>{{product.id}}</td>
                                    <td>{{product.title}}</td>
                                    <td>{{product.brand}}</td>
                                    <td>{{product.quantity}}</td>
                                    <td class="d-none d-lg-table-cell">{{product.cost_price}}</td>
                                    <td class="d-none d-lg-table-cell">{{product.selling_price}}</td>
                                    <td class="d-none d-lg-table-cell">{{product.description}}</td>
                                    <td class="text-center">
                                        <div class="btn-group" role="group">
                                            <a href="{% url 'product_detail' product.id %}" class="btn btn-info btn-sm mx-1">
                                                <i class="bi bi-eye"></i>
                                            </a>
                                            <a href="{% url 'product_update' product.id %}" class="btn btn-warning btn-sm mx-1">
                                                <i class="bi bi-pencil"></i>
                                            </a>
                                            <a href="{% url 'product_delete' product.id %}" class="btn btn-danger btn-sm mx-1">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% include 'components/_pagination.html' %}
{% endblock %}

products/templates/product_update.html
{% extends 'exemplo.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="h-4">Editar Produto</h3>
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn bg-custom">Salvar Produto</button>
            </form>
            <a href="{% url 'product_list' %}" class="btn bg-danger-subtle text-danger-emphasis mt-3">Voltar para a Lista de Produtos</a>
        </div>
    </div>
    
</div>

{% endblock %}